services:
  mysql:
    image: mysql:8.0
    container_name: recipe_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: teste_receitas_rg_sistemas
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - recipe_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_NAME=RecipeHub
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=teste_receitas_rg_sistemas
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - L5_SWAGGER_CONST_HOST=http://localhost:8000
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - recipe_network
    command: >
      bash -c "
      sleep 5 &&
      php artisan migrate --force &&
      php artisan db:seed --force &&
      php artisan l5-swagger:generate &&
      php artisan config:clear &&
      php artisan cache:clear &&
      /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
      "

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: recipe_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - recipe_network

volumes:
  mysql_data:
    driver: local

networks:
  recipe_network:
    driver: bridge